// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPb1wKe0DLcXHZ434HVn0IYhUyo1m5qoo',
    appId: '1:775073250611:web:676fc3f785d17873771246',
    messagingSenderId: '775073250611',
    projectId: 'flutter-project13',
    authDomain: 'flutter-project13.firebaseapp.com',
    storageBucket: 'flutter-project13.appspot.com',
    measurementId: 'G-DSZ8YRXYV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmIgP-MJjz7mCeJ48hhhcpiBbmxc8NCZ8',
    appId: '1:775073250611:android:5d7334f4faf517f7771246',
    messagingSenderId: '775073250611',
    projectId: 'flutter-project13',
    storageBucket: 'flutter-project13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXetnvUGwUFeRGr9yV7jhYrqtzc3WnSwg',
    appId: '1:775073250611:ios:38dbd93e50637afa771246',
    messagingSenderId: '775073250611',
    projectId: 'flutter-project13',
    storageBucket: 'flutter-project13.appspot.com',
    iosClientId: '775073250611-a235nshdj83vic1m4pu21c2bei7c7ls0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXetnvUGwUFeRGr9yV7jhYrqtzc3WnSwg',
    appId: '1:775073250611:ios:38dbd93e50637afa771246',
    messagingSenderId: '775073250611',
    projectId: 'flutter-project13',
    storageBucket: 'flutter-project13.appspot.com',
    iosClientId: '775073250611-a235nshdj83vic1m4pu21c2bei7c7ls0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
